name: audit

on:
  schedule:
    # run every Saturday at midnight
    - cron: '0 0 * * 6'
  push:
    branches: ['**']
    paths:
      - "Cargo.lock"
      - ".github/workflows/audit.yml"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        submodules: true

    - uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 #v1.2.7
