name: pkgcruft-git-release

on:
  push:
    tags: ['pkgcruft-git-*']
    branches: ['**']
    paths:
      - ".github/workflows/pkgcruft-git-release.yml"
      - "crates/pkgcruft-git/Cross.toml"
  workflow_dispatch:

jobs:
  source:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install protoc for arcanist
      uses: taiki-e/install-action@protoc

    - name: Create vendored release
      run: .ci/vendor-release pkgcruft-git

    - name: Create archive
      run: |
        # create the release tarball
        tar -cv -I "xz -9 -T0" -f ${{ github.ref_name }}.tar.xz ${{ github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: source
        path: ./*.tar.xz
        if-no-files-found: error
        retention-days: 3

  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build pkgcruft-git
      run: cross build --target ${{ matrix.target }} --profile release-strip -p pkgcruft-git

    - name: Create archive
      run: |
        tar -C target/${{ matrix.target }}/release-strip \
          -cv -I "xz -9 -T0" -f ${{ github.ref_name }}-${{ matrix.target }}.tar.xz \
          pkgcruft-git pkgcruft-gitd pkgcruft-git-pre-commit pkgcruft-git-pre-push

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}-${{ matrix.target }}
        path: ./*.tar.xz
        if-no-files-found: error
        retention-days: 3

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [source, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.tar.xz
        fail_on_unmatched_files: true
