name: pkgcruft-release

on:
  push:
    tags: ['pkgcruft-[0-9]*']
    branches: ['**']
    paths:
      - ".github/workflows/pkgcruft-release.yml"
  workflow_dispatch:

jobs:
  msrv:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.msrv.outputs.version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the minimum supported rust version (MSRV)
      id: msrv
      run: |
        version=$(sed -rn '/^rust-version\s*=/ s/^.*=\s*"([0-9](\.[0-9]+)+)(.*)/\1/p' Cargo.toml)
        if [[ -n ${version} ]]; then
          echo "version=${version}" >> $GITHUB_OUTPUT
        else
          exit 1
        fi

  shell:
    needs: msrv
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ needs.msrv.outputs.version }}

    - name: Generate files
      run: cargo run --bin pkgcruft completion --dir shell

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shell
        path: shell
        if-no-files-found: error
        retention-days: 3

  source:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [msrv, shell]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ needs.msrv.outputs.version }}

    - name: Create vendored release
      run: .ci/vendor-release pkgcruft

    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest

    - name: Run tests for vendored release
      run: |
        cp -a ${{ github.ref_name }} ${{ github.ref_name }}-test
        pushd ${{ github.ref_name }}-test
        cargo nextest run --all-features --tests
        popd
        rm -rf ${{ github.ref_name }}-test

    - name: Download shell completion
      uses: actions/download-artifact@v4
      with:
        name: shell
        path: shell

    - name: Create archive
      run: |
        # move shell completion files into the release
        mv shell ${{ github.ref_name }}
        # create the release tarball
        tar -cv -I "xz -9 -T0" -f ${{ github.ref_name }}.tar.xz ${{ github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: source
        path: ./*.tar.xz
        if-no-files-found: error
        retention-days: 3

  linux:
    needs: msrv
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ needs.msrv.outputs.version }}

    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build pkgcruft
      run: cross build --target ${{ matrix.target }} --profile release-strip -p pkgcruft

    - name: Create archive
      run: |
        tar -C target/${{ matrix.target }}/release-strip \
          -cv -I "xz -9 -T0" -f ${{ github.ref_name }}-${{ matrix.target }}.tar.xz \
          pkgcruft

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}-${{ matrix.target }}
        path: ./*.tar.xz
        if-no-files-found: error
        retention-days: 3

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [source, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.tar.xz
        fail_on_unmatched_files: true
